services:
  omniroute:
    image: ghcr.io/diegosouzapw/omniroute:latest
    container_name: kikos_omniroute
    restart: unless-stopped
    ports:
      - "8001:20128"  # OmniRoute usa internamente el puerto 3000
    env_file:
      - .env
    volumes:
      - ./data/omniroute:/app/data
